### ISSUE TITLE
Venues on the Registrations page don't get updated

### ISSUE THREAD

**Issue by demontech** [craigschlegel/registrations-for-the-events-calendar#11]
Hi Craig,

I'm using wp 4.6.1 and your latest version 1.1. I noticed that when I update the venue or send it to the trash, the venues on the registrations tab don't get updated. They kept the old values. The only ones that get updated is when you create a new venue under the location section when you're editing the event.

Please let me know if you need more clarification or screenshots. 

All the other updates I can confirm are working great!

Thanks!

**Comment by craigschlegel** [comment]
Sounds good Marco. I'll take a look at this!

Thanks for trying out the update! I'm going to do some thorough testing myself and release it some time this week in the WordPress.org repo

**Comment by craigschlegel** [comment]
Looks like the event meta does not update when the venue title changes but everything else about the venue does. The events calendar has a function that retrieves the updated title so I changed the code to use that function instead of the meta. Should work properly in the latest commit.
